### ISSUE TITLE
Hello Kate - no Bus-

### ISSUE THREAD

**Issue by McKaNaN** [augisbud/m365_dashboard#1]
Hi.

I installed it and all done! :)

The problem, when I power on M365: LCD shows this message: "Hello Kate - no Bus -" 
Any idea?

**Comment by McKaNaN** [comment]
https://youtu.be/q8CMcGD0eyE

**Comment by augisbud** [comment]
Have you used the schematics provided?
https://camo.githubusercontent.com/a912641249173768ae60670e843c62294d06da4f/68747470733a2f2f656c656374726f2e636c75622f646174612f666f72756d2f6d657373616765732f34323633312f696d616765732f31313636302d313238302e6a7067

**Comment by augisbud** [comment]
Gonna upload an updated version :)

**Comment by augisbud** [comment]
Check out the new code provided, it's a revision from the original one, better ui and stability, however the arduino freezes once in a while, a watchdog seems to help it but not all the time, still looking for a solution 😕

**Comment by McKaNaN** [comment]
Ok! I check it and comment here :)

**Comment by McKaNaN** [comment]
I compiled new code and show this:

![img_6380](https://user-images.githubusercontent.com/26546335/44665628-adff6b00-aa16-11e8-8fa2-a124e94498f0.JPG)

A friend say me that the connection is: 
![image](https://user-images.githubusercontent.com/26546335/44665697-dbe4af80-aa16-11e8-9fff-b9387d50c6ca.png)

Its correct?

**Comment by augisbud** [comment]
![](https://i.imgur.com/dENsELd.jpg)

**Comment by augisbud** [comment]
I use this exact scheme without a problem

**Comment by augisbud** [comment]
Send me a picture of the top part of your scooter with the pcb

**Comment by McKaNaN** [comment]
Nothing. I cant connect BUS with screen.
All time shows same message: "BUS not connected! No data to display!"

I have question: 
![img_6382](https://user-images.githubusercontent.com/26546335/44686059-57f9ea00-aa4d-11e8-8e64-f819fb0b88ca.JPG)

This pins are correct?

**Comment by augisbud** [comment]
Yes the pins are correct, can you unscrew the pcb and send me a pic

**Comment by McKaNaN** [comment]
![img_6384](https://user-images.githubusercontent.com/26546335/44686665-3a2d8480-aa4f-11e8-97ee-c8db08416464.JPG)
![img_6385](https://user-images.githubusercontent.com/26546335/44686666-3ac61b00-aa4f-11e8-968e-89298a5201b4.JPG)
![img_6386](https://user-images.githubusercontent.com/26546335/44686667-3ac61b00-aa4f-11e8-8260-a5f0e9dbb71f.JPG)
![img_6387](https://user-images.githubusercontent.com/26546335/44686668-3ac61b00-aa4f-11e8-880e-9714d37609d1.JPG)

Connections are same at schematics :)

**Comment by augisbud** [comment]
I meant the scooter's pcb

**Comment by augisbud** [comment]
The blue one with the button

**Comment by augisbud** [comment]
Ok, I'm going to flash the firmware to my scooter to make sure it's ok

**Comment by McKaNaN** [comment]
![foto 27-8-18 17 01 14](https://user-images.githubusercontent.com/26546335/44687749-49620180-aa52-11e8-9d40-337cbeb3a585.jpg)

I used this connection picture. I think that is the same that you but I cant understand where is the problem :(

**Comment by augisbud** [comment]
Me neither, are those really 1n4148 diode, 120 resistor?

**Comment by McKaNaN** [comment]
![image](https://user-images.githubusercontent.com/26546335/44687876-b4133d00-aa52-11e8-81de-4f59d0b129b6.png)
This is the resistor

Diode shows:
PH
41
48

Is correct?

**Comment by augisbud** [comment]
You might wanna try a 1n4148 diode although they seem to be very similar

**Comment by McKaNaN** [comment]
I dont know....
I need to go to buy new diode.
I change + and - of diode, and shows same message :(

OMG

**Comment by chriskross** [comment]
Have you connect the same gnd for arduino and pcb?

**Comment by McKaNaN** [comment]
Yes! The GND of Bluetooth PCB in GND of Arduino Mini Pro
