### ISSUE TITLE
How to connect the arduino without soldering into m365 pcb?

### ISSUE THREAD

**Issue by carlosmellado** [augisbud/m365_dashboard#19]
Hi guys,
I know this is not an issue, but I don't know where to write it, so, feel free to move it or whatever if you want.

I saw that there is a "connector" 3D model on 3D folder, but... What kind of connectors goes in?
I mean, what should we do with this 3D piece? I would like to implement this in my scooter but it would be nice if I didn't have to solder nothing directly on the board.

Any help would be appreciated!

**Comment by pikselq** [comment]
Hi,
Look at last photo
https://www.ebay.co.uk/itm/OSD-Data-Display-for-Xiaomi-Mijia-M365-Screen-0-96-Dashboard-Waterproof-IPX2-/263945593704
