### ISSUE TITLE
M365 languages translation

### ISSUE THREAD

**Issue by AntoineWaes** [augisbud/m365_dashboard#2]
Hey ! I can provide you my language.h file in French if you want to add it to the files ;) 
Maybe you could do a video showing how to plug and solder the wires 

Thanks for the sharing, and nice work dude !

**Comment by AntoineWaes** [comment]
Thanks a lot for the screens ! The wiring doesn't seems to work for me, it keeps saying 'No bus connected" .. And the M365 shows the 4 LEDS on (with one green)...

**Comment by augisbud** [comment]
Have you connected the resistors and the diode
?

**Comment by AntoineWaes** [comment]
Yes, this is what I did, is it OK ? 
![img_0224](https://user-images.githubusercontent.com/35507692/44617574-23c3d500-a865-11e8-8574-9da4482198d5.jpg)

**Comment by augisbud** [comment]
No let me get a piece of paper quick

**Comment by AntoineWaes** [comment]
Thanks

**Comment by augisbud** [comment]
https://photos.app.goo.gl/1Zbvogu9Ag9gwViG6

**Comment by AntoineWaes** [comment]
This is mine : still not working, and this is what you sent .. What firmware do you have ?
![img_0225](https://user-images.githubusercontent.com/35507692/44617631-620dc400-a866-11e8-8285-413adbe4276f.jpg)

**Comment by augisbud** [comment]
1.4.0, do they have a common ground? I.E The ground and vcc of the arduino is soldered to the scooter

**Comment by AntoineWaes** [comment]
Yeah they are both connected to the  Arduino from the scooter

**Comment by augisbud** [comment]
Hmmm, ok, what chip is that?
https://i.imgur.com/VHPWohZ.png Here's how to connect it

**Comment by AntoineWaes** [comment]
Do you know if there is a difference btw T4148 and 1N4148 diode ? Because I have a T4148

**Comment by augisbud** [comment]
It might be the case, no, not really

**Comment by augisbud** [comment]
I think that's something to do with the arduino not sure yet

**Comment by AntoineWaes** [comment]
The resistor is a 120ohm right ?

**Comment by augisbud** [comment]
Yes

**Comment by AntoineWaes** [comment]
I try a different Arduino, now it is a Arduino Nano. Can you provide a picture of your installation ? With the Arduino ? It still doesn't work .. I'm pretty much desperated right now

**Comment by augisbud** [comment]
Use the 1N4148 Diode, and the schematics provided in the wiki

**Comment by augisbud** [comment]
I'm not home rn so I can't help

**Comment by augisbud** [comment]
This is what I found browsing russian forums about your issue
---Russian Forums---
In general, I realized the problem with nano. CH340, which stands in them, does not fall into any sleep mode, but constantly pulls TX to plus through a 1kΩ resistor. Accordingly, the bus levels are shifted upwards and the scooter ceases to perceive them.
