### ISSUE TITLE
Scooter brakes itself every 3-4 seconds

### ISSUE THREAD

**Issue by carlosmellado** [augisbud/m365_dashboard#20]
Hello again,
I downloaded the last code and installed the arduino today, and the speedometer doesn't update, per instance, it shows 6.0Km/h and it keeps frozen until I break and run again, showing another number that it doesn't corresponds with my current speed.

Also, and the worst, the scooter breaks using the motor, every 3-4 seconds, maybe more, but it's doing driving impossible...

Any suggestions?

**Comment by augisbud** [comment]
use an older version

**Comment by augisbud** [comment]
https://github.com/augisbud/m365_dashboard/tree/fe808eb38dab5e830124fd2576c1aa4a17ca16ec

**Comment by augisbud** [comment]
Check the new source.

**Comment by carlosmellado** [comment]
Tested and it's working fine now.

But you have a syntax error on your last commit at line 244, you have to remove the last parenthesis:

```
//m365_info.sph = abs(S23CB0.speed) / 1000L); // speed (BAD)
m365_info.sph = abs(S23CB0.speed) / 1000L; // speed (GOOD)
```

Thanks a lot!

**Comment by augisbud** [comment]
thank you too, let me know if it freezes

**Comment by carlosmellado** [comment]
Hi there,
I confirm that it's still freezing. Yesterday I tested it 5 minutes and no freezes ocurred.
But today, I did 10km and on every first gas, the speedometer freezes. Sometimes the watchdog works, others not. I restarted my scooter with the same luck. Frozen on the first gas :(

**Comment by augisbud** [comment]
Does your code contain this?
```
  // CURRENT SPEED CALCULATE ALGORYTHM
  if (S23CB0.speed < -10000) {// If speed if more than 32.767 km/h (32767)
    c_speed = S23CB0.speed + 32768 + 32767; // calculate speed over 32.767 (hex 0x8000 and above) add 32768 and 32767 to conver to unsigned int
  } else {
    c_speed = abs(S23CB0.speed); }; //always + speed, even drive backwards ;)
```

**Comment by carlosmellado** [comment]
> Does your code contain this?
> 
> ```
>   // CURRENT SPEED CALCULATE ALGORYTHM
>   if (S23CB0.speed < -10000) {// If speed if more than 32.767 km/h (32767)
>     c_speed = S23CB0.speed + 32768 + 32767; // calculate speed over 32.767 (hex 0x8000 and above) add 32768 and 32767 to conver to unsigned int
>   } else {
>     c_speed = abs(S23CB0.speed); }; //always + speed, even drive backwards ;)
> ```

Yes, I pulled the code yesterday, and this piece of code seems to be pushed 2 days ago.

**Comment by augisbud** [comment]
` long _speed;
  unsigned long c_speed; //current speed`

can you try this?

**Comment by carlosmellado** [comment]
> ` long _speed; unsigned long c_speed; //current speed`
> 
> can you try this?

I will try when I can. I have the arduino hidden on the chassis and I have to unmount the chassis in order to have access to it.

**Comment by augisbud** [comment]
me too :(

**Comment by lukaszlukasz0** [comment]
I corrected the variables to "long" and changed assignments (unsigned long).
Check pull request :)

**Comment by augisbud** [comment]
pulled

**Comment by carlosmellado** [comment]
I pulled the last version and the scooter doesn't brake like before, at least, it seems to work well in my last 3 trips (10 km each one). The speedometer just froze once.

But... I don't know if it's a coincidence, but yesterday, when I powered on the front light, the scooter started braking a lot of times per second on the motor... A soft brakes but you could felt them...

I had to restart the scooter and continue driving without light.

Today I will try again to see if it reproduces again.

**Comment by carlosmellado** [comment]
> You need to replace F2 fuse, on the motherboard.

Why? 🤔

**Comment by lukaszlukasz0** [comment]
Because its broken 😁

you describe a light defect that is directly related to the damage of this fuse.

**Comment by carlosmellado** [comment]
Well, will try again today and I will tell you later 😄

Thanks!

**Comment by lukaszlukasz0** [comment]
This help
http://imgur.com/gallery/Yirukc9

This is self resetting Fuse, need to be 500mA

**Comment by carlosmellado** [comment]
Somebody knows the fuse characteristics?

Is this one valid? 
[Ebay Link](https://www.ebay.es/itm/5-X-1206L050YR-Fuse-PTC-polymer-500mA-1206L/112699733600?hash=item1a3d6d7660:i:112699733600:rk:6:pf:0)
