### ISSUE TITLE
No S25C31 data

### ISSUE THREAD

**Issue by FlexH** [augisbud/m365_dashboard#30]
Hi, 

I'm using an Adafruit Pro Trinket and i've got a problem :
Connection to the M365 is OK beacause using https://github.com/fogbox/m365_display in PASSIVE_MODE I can view throttle and brake status.

But I don't have any data from the S25C31 (current, voltage, etc...). All is 0.

You are testing these values on line 61

> if ((S25C31.current == 0) && (S25C31.voltage == 0) && (S25C31.remainPercent == 0))

Do you have infos about this problem ?

Regards,

**Comment by augisbud** [comment]
It may be that either the diode or the resistor aren't correct, the resistors should be 1% tolerance, atleast that's what works for most
