### ISSUE TITLE
Cruise Control Kers tail light

### ISSUE THREAD

**Issue by afonsos** [augisbud/m365_dashboard#32]
Im trying to change cruise control to ON,default is off.Change to ON then update cruise.
It stays ON but after next boot it goes to OFF again.
Im on an october release is this ok on recent updates? I didnt uploaded new code yet because Im not sure if its solved now and its a pain to get to arduino :)
Thanks for your work pretty simple to build this dash and awesome features

**Comment by augisbud** [comment]
It hasn't been patched yet, it will be

**Comment by augisbud** [comment]
@afonsos I have patched it, give it a try

**Comment by afonsos** [comment]
Thanks for the patch augisbud

Im getting this error compiling sketch

M365:235: error: conflicting declaration 'unsigned int c_speed'

   unsigned int c_speed; //current speed

                ^

M365:234: error: 'c_speed' has a previous declaration as 'long int c_speed'

   long c_speed; //current speed

        ^

exit status 1
conflicting declaration 'unsigned int c_speed'

**Comment by augisbud** [comment]
give it a try @afonsos

**Comment by augisbud** [comment]
for me it compiles, haven't uploaded it to the scooter

**Comment by afonsos** [comment]
works as expected.
Thanks mate
