### ISSUE TITLE
Question about the resistor

### ISSUE THREAD

**Issue by Synced21** [augisbud/m365_dashboard#33]
Can someone explain me the purpose of the resistor? Does the resistor not also block the data that is coming for the TX0 pin.

Thank your four your help guys.

**Comment by Synced21** [comment]
For any interest:

The idle state of a serial line is HIGH. Transmission starts with a start-bit which is a LOW and ends with 1/1.5/2 stop-bits which are HIGH.

The diode and resistor prevent the corruption; the M365 can still pull the line LOW.

**Comment by rediculum** [comment]
Does it need to be exactly 120Ohm? I only have 100 or 150Ohm as spare.

**Comment by NetBUG** [comment]
Hi @rediculum , 100 Ohm works perfectly.
