### ISSUE TITLE
Restarts on turning light on

### ISSUE THREAD

**Issue by marioinz** [augisbud/m365_dashboard#34]
Hi. 
Mine dashboard keeps restarting (or turns of after a few restarts) when front light is turn on: https://youtu.be/BllbipDUYU8
My display is 4 wire SPI - this is only diffrence to your recomendations (i only changed defines and display initalization method). 
What may case such behavior ?

**Comment by lukaszlukasz0** [comment]
Check the fuse f2 on mainboard.

**Comment by augisbud** [comment]
@marioinz as Lukas said, check the second fuse on the main board, and try to flash the i2c code to see if it's the issue

**Comment by marioinz** [comment]
ok. thx I will go with f2 fuse inspection ang get back heare with results. thank for quick response!

**Comment by marioinz** [comment]
ok guys you were right. it is f2 fuse issue - i also have engine disruptions when lights is on. current resistance of fuse is ~2ohms.
what replace can i apply ? will this fit: http://electropark.pl/smd/3717-bezpiecznik-polimerowy-500ma-1812.html ? 
thanks in advance

**Comment by augisbud** [comment]
@marioinz it's because the display is restarting, not sure what fuse you need

**Comment by lukaszlukasz0** [comment]
@marioinz 500mA is ok. Like original..

**Comment by marioinz** [comment]
thanks guys! fuse replaced and now everything works just perfect! i bought 3 sizes and 0805 fits perfectly. you can close issue. Best
