### ISSUE TITLE
Display battery with 13s

### ISSUE THREAD

**Issue by Hermit12** [augisbud/m365_dashboard#36]
Hi, 
I made a custom battery pack with 13s, but I can only see cells from 0 to 9, the last 3 voltages are hidden. Is it possible to add a scroll function so that it shows the other cells, lets say, every 3-4 seconds?

Regards

**Comment by augisbud** [comment]
The code is able to handle up to 15 cells 
`struct __attribute__((packed))A25C40 {
  int c1; //cell1 /1000
  int c2; //cell2
  int c3; //etc.
  int c4;
  int c5;
  int c6;
  int c7;
  int c8;
  int c9;
  int c10;
  int c11;
  int c12;
  int c13;
  int c14;
  int c15;
} S25C40;`
Line 146 in defines.h

This is where we display the battery cells info
`int v;
  int * ptr;
  int * ptr2;
  ptr = (int*)&S25C40;
  ptr2 = ptr + 5;
  for (int i = 0; i < 5; i++) {
    display.setCursor(5, 2 + i);
    display.print(i);
    display.print(": ");
    v = *ptr / 1000;
    display.print(v);
    display.print('.');
    v = *ptr % 1000;
    if (v < 100) display.print('0');
    if (v < 10) display.print('0');
    display.print(v);
    display.print((const __FlashStringHelper *) l_v);

    display.setCursor(70, 2 + i);
    display.print(i + 5); 
    display.print(": ");
    v = *ptr2 / 1000;
    display.print(v);
    display.print('.');
    v = *ptr2 % 1000;
    if (v < 100) display.print('0');
    if (v < 10) display.print('0');
    display.print(v);
    display.print((const __FlashStringHelper *) l_v);

    ptr++;
    ptr2++;
  }
`
Line 179 M365.ino
