### ISSUE TITLE
MPH and US Degrees Version?

### ISSUE THREAD

**Issue by pilotdeveloper** [augisbud/m365_dashboard#39]
Happen to have a US Version with MPH and Degrees F?

**Comment by augisbud** [comment]
If you want to do it yourself you just need to convert the values like speed, distance, temperature to us versions, i will start working on it

**Comment by augisbud** [comment]
sph & spl = are speed values, just convert both of them to mph from kmh
milh & mill = are distance values, just convert both of them to miles from kilometres
temp = is the temperature value, just convert it to farenheit

**Comment by pilotdeveloper** [comment]
Yes - I figured it out :)
I *may* do a PR to include it as a localization option for you if that's
cool!

**Comment by augisbud** [comment]
should work, give it a try

**Comment by augisbud** [comment]
make sure you uncomment line 7 in defines.h
