### ISSUE TITLE
Battery Warning issue

### ISSUE THREAD

**Issue by AntoineWaes** [augisbud/m365_dashboard#4]
Hey, 
I finally got the answer for my last issue with the Arduino Nano. Turns out that the baud rate of the M365 is 115200, and only the mini pro has the same. This means that nano won’t work 

I have another issue now : this screen keeps showing every seconds, and I have no idea what it means, and why it’s there for 
Can you help me ?

**Comment by AntoineWaes** [comment]
![img_0268](https://user-images.githubusercontent.com/35507692/44773019-bdde9280-ab6f-11e8-9114-40eee62b2c99.jpg)

**Comment by augisbud** [comment]
Go into settings full brake + full gas, and select battery warning limit

**Comment by augisbud** [comment]
Use brake to surf the menu, and gas to select

**Comment by AntoineWaes** [comment]
Nice ! Thanks a lot
