### ISSUE TITLE
Hibernate feature

### ISSUE THREAD

**Issue by maniakpl** [augisbud/m365_dashboard#41]
Hi guys,
Wanted to add hibernate option to my dashboard. The dashboard must be unpluged from the scooter when changing or updating scooter's firmware, so hibernate option would be perfect for that.
Since I am new to programming, I need your help with this.
What lines of code should I put and where to get this feature?
Regards,
Bartek

**Comment by augisbud** [comment]
i just have a toggle switch for the power of the arduino, not bothering with another menu option, although all you need to do is disable the packet request to accomplish this

**Comment by afonsos** [comment]
![IMG_20190401_092132_HDR](https://user-images.githubusercontent.com/27768037/55881740-24626f00-5b9b-11e9-8f81-e2e151007550.jpg)

**Comment by villamany** [comment]
This will do the job https://github.com/augisbud/m365_dashboard/pull/50
