### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by LukCaha** [augisbud/m365_dashboard#42]
Please, how to change language? When I edit language.h to something like that:
```
//#define Language ENG //English
#define Language FRA //French
//#define Language RU //Russian, use together with the russian font in libraries folder
//#define Language ES //Spanish
```
language is still ENG.

**Comment by villamany** [comment]
I don,t know what is the exact error, maybe de POGMEM sentence not valid with compiler directives??? But if you cut and paste the lines of your language in the first place it will take effect

**Comment by villamany** [comment]
Fixed https://github.com/augisbud/m365_dashboard/pull/55

**Comment by LukCaha** [comment]
It works! Thanx!
