### ISSUE TITLE
Temperature 

### ISSUE THREAD

**Issue by afonsos** [augisbud/m365_dashboard#53]
Not really an issue as we can live with that :)
Does yours show temp higher than on android apps like tools for ex.? 10ºC difference.
Today it was displaying 40ºC connected tools and it was 28/30

**Comment by augisbud** [comment]
The temperature you see in stationary isn't the battery temperature, it's the vehicle body temperature, you will see the battery temperature while charging. Here are some pics from my testing.
[Scooter Display](https://i.imgur.com/mxWCxUv.jpg)
[M365 Dashboard on Android](https://i.imgur.com/0EPj9uZ.jpg)
[M365 Tools on Android](https://i.imgur.com/NWnBVCL.jpg)

**Comment by afonsos** [comment]
Thats right,my fault :)
Thanks augis
