### ISSUE TITLE
Display ECO mode

### ISSUE THREAD

**Issue by LukCaha** [augisbud/m365_dashboard#57]
Is it possible to indicate ECO mode on the display?
I tried looking in the code but without success.

**Comment by villamany** [comment]
Checking the file "defines.h" seems to be stored in "S21C00HZ64.state" var where //0-stall, 1-drive, 2-eco stall, 3-eco drive

**Comment by augisbud** [comment]
unless you use a bigger display than 0.96" displaying the presence of eco mode is kinda useless since we still have the 4 notification leds, but @villamany is right
