### ISSUE TITLE
Cambio por Nano

### ISSUE THREAD

**Issue by pedrinterremoto** [augisbud/m365_dashboard#6]
Good morning, a question, could I change the pro mini for a nano?
would it be igd? greetings and thanks.

**Comment by augisbud** [comment]
The nano has a programmer which doesn't go to sleep, and I think there are some issues with the baundrate, check the closed issues to see for yourself.

**Comment by chriskross** [comment]
I have a solution for nano 😋
I test it and I'll post it ( if work fine!)

**Comment by pedrinterremoto** [comment]
Ok gracias, lo agradecería mucho que se publicará. Saludos
