### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by jasiekxl** [augisbud/m365_dashboard#68]
I did everything like is wrote  and screen is black,

**Comment by dimitrisdaniil** [comment]
You should probably check the first lines of the code where it chooses between spi and i2c protocolls
(correct me if i am wrong - newbie though -but i fix it this way)

**Comment by satan671** [comment]
I had the same problem and by default is DISPLAY_SPI in file defines.h

**Comment by dimitrisdaniil** [comment]
Yes thats it
