### ISSUE TITLE
oled ssd1106 wrong visualization

### ISSUE THREAD

**Issue by esaltarelli** [augisbud/m365_dashboard#69]
I tried to connect an oled SSH1106 panel, but its operation is not 100%.
The first column of pixels is not displayed while at the end of the screen an incorrect one is displayed.
As if the image were shifted one pixel to the left.
Can you help me?

**Comment by LukCaha** [comment]
Really SSD1106? or you mean SH1106? Use the correct display SSD**13**06

**Comment by esaltarelli** [comment]
Aorry, my mistake is an SSH1106, I change it immediately.
