### ISSUE TITLE
Could that work on the Pro ? 

### ISSUE THREAD

**Issue by PeterMikeSmooth** [augisbud/m365_dashboard#71]
Hello ! 

Thanks for that cool project !

Pro dashboard only has speed indicator. It would be great to have all these additional informations on the Pro. 

However Pro bluetooth board runs on ble90 firmware. And classic on ble72 firmware. 

Apparently the one-wire protocole is different on these two firmwares. 

How hard would it be to make this project compatible with ble90 (i.e. Pro scooters) ? 

Thank you !

**Comment by PeterMikeSmooth** [comment]
Nobody ?

**Comment by augisbud** [comment]
I don't think so, the firmware is different
