### ISSUE TITLE
Greek Symbol Font

### ISSUE THREAD

**Issue by rediculum** [augisbud/m365_dashboard#75]
Hi

After successfully flashing the code, I get some kind of greek symbols as font. In language.h I have
```
#define LANG_ENG //English
``` 
and in defines.h
```
#define DISPLAY_I2C

#define US_Version
```
![20200602_201353](https://user-images.githubusercontent.com/8666333/83554964-d9798880-a50d-11ea-9be9-02b16d2c0e55.jpg)

**Comment by nextor11** [comment]
That greek is definitely russian.

It's telling you "bus not connected". Your arduino is not communicating with the scooter.

**Comment by rediculum** [comment]
@nextor11 I knew the message because I haven't connected it yet to the scooter, but now do I change the language to english?

**Comment by rediculum** [comment]
@nextor11 thanks, that changed to english
