### ISSUE TITLE
Unable to use en language 

### ISSUE THREAD

**Issue by Frog9920** [augisbud/m365_dashboard#78]
I unconnected the EN language from the language.h and Russian can’t be changed .

**Comment by augisbud** [comment]
Can't talk now.

**Comment by ArduinoTT** [comment]
Need write this

#include "fonts/m365.h"/*
#if LANG == RU
  #include "fonts/System5x7ru.h"
#else*/
  #include "fonts/System5x7mod.h"/*
#endif*/

![image](https://user-images.githubusercontent.com/72885993/96029814-7274c480-0e5b-11eb-8a29-f881692ec043.png)

and need uncomment your favorite language in language.h
